package com.lzz.util;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;

/**
 * Created by lzz on 17/4/10.
 */
public class Sqlite {
    private static Sqlite sqlite;
    private JdbcTemplate jdbcTpl;

    public static Sqlite getSqlite(){
        if( sqlite == null ){
            ApplicationContext ctx = new ClassPathXmlApplicationContext("applicationContext.xml");
            sqlite = (Sqlite) ctx.getBean("sqlite");
            return sqlite;
        }
        return sqlite;
    }
    /**
     *  插入一条数据
     * @param sql
     * @return
     */
    public int insert(String sql){
        int res = jdbcTpl.update(sql);
        return res;
    }

    /**
     * 获取 roles 列表
     * @return
     */
    public List select(String sql){
        List list = jdbcTpl.queryForList(sql);
        return list;
    }

    public boolean initDB(){
        // 创建 roles 表
        jdbcTpl.execute("CREATE TABLE if not exists roles(" +
                "id int  GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, " +
                "role_name VARCHAR(100), " +
                "service VARCHAR(100), " +
                "type VARCHAR(20), " +
                "ping_url VARCHAR(255), " +
                "metric VARCHAR(20), " +
                "client_id VARCHAR(255), " +
                "members VARCHAR(255), " +
                "add_time int)");
        // 创建 send_logs 表
        jdbcTpl.execute("create table if not exists send_logs(" +
                "id int  GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, " +
                "roleid int, " +
                "service VARCHAR(100), " +
                "type VARCHAR(20), " +
                "ping_url VARCHAR(255), " +
                "metric VARCHAR(20), " +
                "error_message VARCHAR(255), " +
                "error_code int, " +
                "members VARCHAR(255), " +
                "add_time int," +
                "day int," +
                "hour int," +
                "minute int," +
                ")");
        return true;
    }

    public void setJdbcTpl(JdbcTemplate jdbcTpl) {
        this.jdbcTpl = jdbcTpl;
    }
}
